use_default_settings: true

server:
  secret_key: "useless-useless-useless-useless-useless"
  limiter: false
  port: 8080
  bind_address: "0.0.0.0"

search:
  formats:
    - html
    - json
  safe_search: 0
  default_lang: "en"
  autocomplete: ""

outgoing:
  request_timeout: 10.0
  max_request_timeout: 15.0
  max_retries: 2
  retries: 2
  enable_http2: true
  source_ips:
    - 0.0.0.0
  headers:
    User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"

redis:
  url: redis://redis:6379
  db: 0
  timeout: 5.0
  max_connections: 100
  min_connections: 10
  connection_timeout: 5.0
