import { mkdir, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

const mockGetArtifactForUser = vi.fn();
const mockGetSourceArtifactId = vi.fn();
const mockResolveGeneratedFileServing = vi.fn();

vi.mock("./core", () => ({
	getArtifactForUser: (...args: unknown[]) => mockGetArtifactForUser(...args),
	getSourceArtifactIdForNormalizedArtifact: (...args: unknown[]) =>
		mockGetSourceArtifactId(...args),
}));

vi.mock("$lib/server/services/generated-file-serving", () => ({
	resolveGeneratedFileServing: (...args: unknown[]) =>
		mockResolveGeneratedFileServing(...args),
}));

import { resolveWorkingDocumentFileServing } from "./working-document-file-serving";

async function writeKnowledgeFile(
	storagePath: string,
	contents: Buffer | string,
) {
	const absolutePath = join(process.cwd(), storagePath);
	await mkdir(dirname(absolutePath), { recursive: true });
	await writeFile(absolutePath, contents);
}

describe("resolveWorkingDocumentFileServing", () => {
	const userId = "resolver-user-123";

	beforeEach(() => {
		vi.clearAllMocks();
		mockGetSourceArtifactId.mockResolvedValue(null);
		mockResolveGeneratedFileServing.mockResolvedValue({
			ok: false,
			status: 404,
			error: "File not found",
		});
	});

	afterEach(async () => {
		await rm(join(process.cwd(), "data", "knowledge", userId), {
			recursive: true,
			force: true,
		});
	});

	it("resolves a normalized document to its source binary for preview", async () => {
		const pdfBuffer = Buffer.from("PDF binary content");
		await writeKnowledgeFile(
			"data/knowledge/resolver-user-123/source.pdf",
			pdfBuffer,
		);

		mockGetArtifactForUser.mockImplementation(
			async (_userId: string, artifactId: string) => {
				if (artifactId === "normalized-123") {
					return {
						id: "normalized-123",
						name: "document.pdf",
						storagePath: null,
						contentText: "Extracted text content",
						mimeType: "text/plain",
						extension: "pdf",
						type: "normalized_document",
					};
				}

				if (artifactId === "source-123") {
					return {
						id: "source-123",
						name: "document.pdf",
						storagePath: "data/knowledge/resolver-user-123/source.pdf",
						contentText: null,
						mimeType: "application/pdf",
						extension: "pdf",
						type: "source_document",
					};
				}

				return null;
			},
		);
		mockGetSourceArtifactId.mockResolvedValue("source-123");

		const result = await resolveWorkingDocumentFileServing({
			userId,
			artifactId: "normalized-123",
			mode: "preview",
		});

		expect(result.ok).toBe(true);
		if (!result.ok) throw new Error("expected successful resolution");
		expect(result.headers["Content-Type"]).toBe("application/pdf");
		expect(result.headers["Content-Disposition"]).toContain("document.pdf");
		expect(Buffer.from(result.body).toString()).toBe("PDF binary content");
	});

	it("delegates generated output source chat files to generated file serving", async () => {
		const delegatedResult = {
			ok: true,
			body: new Uint8Array(Buffer.from("generated bytes")),
			headers: {
				"Content-Type": "application/pdf",
				"Content-Length": "15",
				"Content-Disposition": 'inline; filename="generated_report.pdf"',
				"Cache-Control": "private, max-age=3600",
			},
		};
		mockGetArtifactForUser.mockResolvedValue({
			id: "generated-123",
			name: "generated_report.pdf",
			storagePath: null,
			contentText: "Some generated text summary",
			mimeType: "text/plain",
			extension: "pdf",
			type: "generated_output",
			metadata: { sourceChatFileId: "chatfile-456" },
		});
		mockResolveGeneratedFileServing.mockResolvedValue(delegatedResult);

		const result = await resolveWorkingDocumentFileServing({
			userId,
			artifactId: "generated-123",
			mode: "preview",
		});

		expect(result).toBe(delegatedResult);
		expect(mockResolveGeneratedFileServing).toHaveBeenCalledWith({
			userId,
			fileId: "chatfile-456",
			mode: "preview",
			displayFilename: "generated_report.pdf",
		});
	});

	it("does not serve failed source-first generated document text as a preview", async () => {
		mockGetArtifactForUser.mockResolvedValue({
			id: "generated-failed",
			name: "failed_report.pdf",
			storagePath: null,
			contentText: "Failed report source projection",
			mimeType: "application/vnd.alfyai.generated-document+json",
			extension: "alfyidoc.json",
			type: "generated_output",
			metadata: {
				generatedDocumentSourceVersion: 1,
				generatedDocumentSourceStatus: "failed",
			},
		});

		const result = await resolveWorkingDocumentFileServing({
			userId,
			artifactId: "generated-failed",
			mode: "preview",
		});

		expect(result).toEqual({
			ok: false,
			status: 404,
			error: "File not available for preview",
		});
		expect(mockResolveGeneratedFileServing).not.toHaveBeenCalled();
	});

	it("does not serve pending source-first generated document text as a download", async () => {
		mockGetArtifactForUser.mockResolvedValue({
			id: "generated-pending",
			name: "pending_report.pdf",
			storagePath: null,
			contentText: "Pending report source projection",
			mimeType: "application/vnd.alfyai.generated-document+json",
			extension: "alfyidoc.json",
			type: "generated_output",
			metadata: {
				generatedDocumentSourceVersion: 1,
				generatedDocumentSourceStatus: "pending",
			},
		});

		const result = await resolveWorkingDocumentFileServing({
			userId,
			artifactId: "generated-pending",
			mode: "download",
		});

		expect(result).toEqual({
			ok: false,
			status: 404,
			error: "File not available for download",
		});
		expect(mockResolveGeneratedFileServing).not.toHaveBeenCalled();
	});

	it("keeps the requested normalized document filename when downloading source bytes", async () => {
		const pdfBuffer = Buffer.from("PDF binary content");
		await writeKnowledgeFile(
			"data/knowledge/resolver-user-123/source.pdf",
			pdfBuffer,
		);
		mockGetArtifactForUser.mockImplementation(
			async (_userId: string, artifactId: string) => {
				if (artifactId === "normalized-123") {
					return {
						id: "normalized-123",
						name: "requested-name",
						storagePath: null,
						contentText: "Extracted text content",
						mimeType: "text/plain",
						extension: "pdf",
						type: "normalized_document",
					};
				}

				if (artifactId === "source-123") {
					return {
						id: "source-123",
						name: "source-name.pdf",
						storagePath: "data/knowledge/resolver-user-123/source.pdf",
						contentText: null,
						mimeType: "application/pdf",
						extension: "pdf",
						type: "source_document",
					};
				}

				return null;
			},
		);
		mockGetSourceArtifactId.mockResolvedValue("source-123");

		const result = await resolveWorkingDocumentFileServing({
			userId,
			artifactId: "normalized-123",
			mode: "download",
		});

		expect(result.ok).toBe(true);
		if (!result.ok) throw new Error("expected successful resolution");
		expect(result.headers["Content-Disposition"]).toBe(
			"attachment; filename*=UTF-8''requested-name.pdf",
		);
		expect(Buffer.from(result.body).toString()).toBe("PDF binary content");
	});

	it("resolves a text-only Skill Note for download", async () => {
		const contentText = "Private note content";
		mockGetArtifactForUser.mockResolvedValue({
			id: "skill-note-123",
			name: "Skill Note",
			storagePath: null,
			contentText,
			mimeType: "text/plain",
			extension: "md",
			type: "skill_note",
			metadata: null,
		});

		const result = await resolveWorkingDocumentFileServing({
			userId,
			artifactId: "skill-note-123",
			mode: "download",
		});

		expect(result.ok).toBe(true);
		if (!result.ok) throw new Error("expected successful resolution");
		expect(result.headers["Content-Type"]).toBe("text/plain; charset=utf-8");
		expect(result.headers["Content-Disposition"]).toBe(
			"attachment; filename*=UTF-8''Skill%20Note.md",
		);
		expect(result.headers["Cache-Control"]).toBe("private, no-store");
		expect(Buffer.from(result.body).toString()).toBe(contentText);
	});
});
